### ISSUE TITLE
Блок - двойные пробелы

### ISSUE THREAD

**Issue by Smittsam** [bonjonson/vtmb20bot#2]
двойные пробелы между словами, орфография сохранена:
"Проверка ловкости + драки позволяет персонажу    использовать собственное тело для отражения вражеских атак в ближнем бою.    Если персонаж не облачён в броню или не является адептом Стойкости, то    он может блокировать только атаки, наносящие лёгкие повреждения."

**Comment by bonjonson** [comment]
Fixed
