### ISSUE TITLE
Парирование

### ISSUE THREAD

**Issue by Smittsam** [bonjonson/vtmb20bot#3]
Двойные пробелы между словами + регистр
"проверка ловкости + фехтования позволяет блокировать любую    атаку в ближнем бою.   Если персонаж атакует без оружия, а противник   пытается блокировать его атаку оружием, которое   обычно наносит тяжёлые повреждения, атакующий рискует    сам получить урон: если встречную проверку выигрывает    противник, он проходит проверку урона, пул которой    равен урону его оружия,плюс один d10 за каждый    оставшийся у него успех (не считая первого)."

**Comment by bonjonson** [comment]
Fixed
