### ISSUE TITLE
Уклонение

### ISSUE THREAD

**Issue by Smittsam** [bonjonson/vtmb20bot#4]
Регистр, двойные пробелы + единственная ссылка на страницу в рульке, ссылка ни па госту
"проверка ловкости + атлетики позволяет персонажу    уклоняться от любых атак. Для уклонения от атак в ближнем бою    нужно только свободное пространство и возможность свободно    двигаться (в противном случае придётся ограничиться блоками    и парированием). В перестрелке уклонение — это либо стремительный    бросок на расстояние как минимум метра в ближайшее укрытие,    либо (в случае отсутствия укрытия) не менее стремительный переход    в положение лёжа. Пока персонаж лежит или остаётся в укрытии, на    последующие дистанционные атаки против него будут действовать правила,    описанные на стр. 298 книги правил"

**Comment by bonjonson** [comment]
Fixed
